#!/bin/bash
gcc -c 100-atoi.c 9-strcpy.c 6-abs.c 5-strstr.c 4-strpbrk.c 4-isalpha.c 3-strspn.c 3-strcmp.c 3-puts.c 3-islower.c 2-strncpy.c 2-strlen.c 2-strchr.c 1-strncat.c 1-memcpy.c 1-isdigit.c 0-strcat.c 0-memset.c 0-isupper.c 0-putchar.c
